name: Docker Compose Actions Workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo MONGO_DB_LINK=${{ secrets.MONGO_DB_LINK }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo LOAD_API_KEYS=${{ secrets.LOAD_API_KEYS }} >> .env
          echo RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} >> .env
          echo RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }} >> .env
          echo RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} >> .env
          echo CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} >> .env
          echo CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo REDIS_DB=${{ secrets.REDIS_DB }} >> .env
          cat .env
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:api appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/